name: Run format

on:
  pull_request:
  push:
    branches: [main]

# Cancel the runs a newer push to the same branch or PR supersedes.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LLVM_VERSION: "22"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install tools
        uses: ./.github/actions/install-tools
        with:
          llvm-version: ${{ env.LLVM_VERSION }}
          packages: clang-format-${{ env.LLVM_VERSION }}

      # Minimal configuration to setup clang-format only.
      - name: Configure
        run: >
          cmake -S . -B build -G Ninja
          -DMLIR_DIR="/usr/lib/llvm-$LLVM_VERSION/lib/cmake/mlir"
          -DLLVM_DIR="/usr/lib/llvm-$LLVM_VERSION/lib/cmake/llvm"
          -DCLANG_FORMAT="/usr/bin/clang-format-$LLVM_VERSION"
          -DLIBADALANG_INCLUDE_DIR=/tmp/not/needed/to/format

      - name: Run the format target and check for changes
        run: |
          cmake --build build --target format
          git diff --exit-code
